#!/usr/bin/env python
import optparse
import sys
from collections import defaultdict

optparser = optparse.OptionParser()
optparser.add_option("-d", "--data", dest="train", default="data/hansards", help="Data filename prefix (default=data)")
optparser.add_option("-e", "--english", dest="english", default="e", help="Suffix of English filename (default=e)")
optparser.add_option("-f", "--french", dest="french", default="f", help="Suffix of French filename (default=f)")
optparser.add_option("-t", "--threshold", dest="threshold", default=0.5, type="float", help="Threshold for aligning with Dice's coefficient (default=0.5)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=100000000000, type="int", help="Number of sentences to use for training and alignment")
(opts, _) = optparser.parse_args()
f_data = "%s.%s" % (opts.train, opts.french)
e_data = "%s.%s" % (opts.train, opts.english)

sys.stderr.write("Training with Dice's coefficient...")
# bitext = [[sentence.strip().split() for sentence in pair] for pair in zip(open(f_data), open(e_data))][:opts.num_sents]


# t = defaultdict(lambda: defaultdict(lambda: 1.0))
# for iteration in range(15):
#     count_ef = defaultdict(float)
#     total_f = defaultdict(float)
#     for (f, e) in bitext:
#         for e_j in e:
#             Z = sum(t[e_j][f_i] for f_i in f)
#             for f_i in f:
#                 c = t[e_j][f_i] / Z
#                 count_ef[(e_j, f_i)] += c
#                 total_f[f_i] += c
#     for (e_j, f_i), value in count_ef.items():
#         t[e_j][f_i] = value / total_f[f_i]
# for (f, e) in bitext:
#     for j, e_j in enumerate(e):
#         best_prob = 0
#         best_i = 0
#         for i, f_i in enumerate(f):
#             if t[e_j][f_i] > best_prob:
#                 best_prob = t[e_j][f_i]
#                 best_i = i
#         sys.stdout.write("%i-%i " % (best_i, j))
#     sys.stdout.write("\n")

def train_ibm1(bitext, num_iters=15, reverse=False):
    if reverse:
        bitext = [(e, f) for (f, e) in bitext]

    t = defaultdict(lambda: defaultdict(lambda: 1.0))
    for iteration in range(num_iters):
        count_ef = defaultdict(float)
        total_f = defaultdict(float)
        for (f, e) in bitext:
            for e_j in e:
                Z = sum(t[e_j][f_i] for f_i in f)
                for f_i in f:
                    c = t[e_j][f_i] / Z
                    count_ef[(e_j, f_i)] += c
                    total_f[f_i] += c
        for (e_j, f_i), value in count_ef.items():
            t[e_j][f_i] = value / total_f[f_i]
    return t

def align_sentence(f, e, t, reverse=False):
    alignment = set()
    if not reverse:  # f→e
        for j, e_j in enumerate(e):
            best_prob, best_i = 0, 0
            for i, f_i in enumerate(f):
                if t[e_j][f_i] > best_prob:
                    best_prob, best_i = t[e_j][f_i], i
            alignment.add((best_i, j))
    else:  # e→f
        for i, f_i in enumerate(f):
            best_prob, best_j = 0, 0
            for j, e_j in enumerate(e):
                if t[f_i][e_j] > best_prob:
                    best_prob, best_j = t[f_i][e_j], j
            alignment.add((i, best_j))
    return alignment

bitext = [[s.strip().split() for s in pair] for pair in zip(open(f_data), open(e_data))][:opts.num_sents]
t_fe = train_ibm1(bitext, num_iters=15, reverse=False)
t_ef = train_ibm1(bitext, num_iters=15, reverse=True)
for (f, e) in bitext:
    A_f2e = align_sentence(f, e, t_fe, reverse=False)
    A_e2f = align_sentence(f, e, t_ef, reverse=True)
    A = A_f2e & A_e2f
    sys.stdout.write(" ".join("%d-%d" % (i, j) for (i, j) in sorted(A)) + "\n")