#!/usr/bin/env python
import optparse
import sys
from collections import defaultdict

optparser = optparse.OptionParser()
optparser.add_option("-d", "--data", dest="train", default="data/hansards", help="Data filename prefix (default=data)")
optparser.add_option("-e", "--english", dest="english", default="e", help="Suffix of English filename (default=e)")
optparser.add_option("-f", "--french", dest="french", default="f", help="Suffix of French filename (default=f)")
optparser.add_option("-t", "--threshold", dest="threshold", default=0.5, type="float", help="Threshold for aligning with Dice's coefficient (default=0.5)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=100000000000, type="int", help="Number of sentences to use for training and alignment")
(opts, _) = optparser.parse_args()
f_data = "%s.%s" % (opts.train, opts.french)
e_data = "%s.%s" % (opts.train, opts.english)

sys.stderr.write("Training with Dice's coefficient...")
bitext = [[sentence.strip().split() for sentence in pair] for pair in zip(open(f_data), open(e_data))][:opts.num_sents]
# f_count = defaultdict(int)
# e_count = defaultdict(int)
# fe_count = defaultdict(int)
# for (n, (f, e)) in enumerate(bitext):
#   for f_i in set(f):
#     f_count[f_i] += 1
#     for e_j in set(e):
#       fe_count[(f_i,e_j)] += 1
#   for e_j in set(e):
#     e_count[e_j] += 1
#   if n % 500 == 0:
#     sys.stderr.write(".")

# dice = defaultdict(int)
# for (k, (f_i, e_j)) in enumerate(fe_count.keys()):
#   dice[(f_i,e_j)] = 2.0 * fe_count[(f_i, e_j)] / (f_count[f_i] + e_count[e_j])
#   if k % 5000 == 0:
#     sys.stderr.write(".")
# sys.stderr.write("\n")

# for (f, e) in bitext:
#   for (i, f_i) in enumerate(f): 
#     for (j, e_j) in enumerate(e):
#       if dice[(f_i,e_j)] >= opts.threshold:
#         sys.stdout.write("%i-%i " % (i,j))
#   sys.stdout.write("\n")

#IBM Model 1
t = defaultdict(lambda: defaultdict(lambda: 1.0))
for iteration in range(10):
    count_ef = defaultdict(float)
    total_f = defaultdict(float)
    for (f, e) in bitext:
        for e_j in e:
            Z = sum(t[e_j][f_i] for f_i in f)
            for f_i in f:
                c = t[e_j][f_i] / Z
                count_ef[(e_j, f_i)] += c
                total_f[f_i] += c
    for (e_j, f_i), value in count_ef.items():
        t[e_j][f_i] = value / total_f[f_i]
for (f, e) in bitext:
    for j, e_j in enumerate(e):
        best_prob = 0
        best_i = 0
        for i, f_i in enumerate(f):
            if t[e_j][f_i] > best_prob:
                best_prob = t[e_j][f_i]
                best_i = i
        sys.stdout.write("%i-%i " % (best_i, j))
    sys.stdout.write("\n")